COLUMNS:
 person_age: float64
 person_gender: object 
 person_education: object 
 person_income: float64
 person_emp_exp: int64  
 person_home_ownership: object 
 loan_amnt: float64
 loan_intent: object 
 loan_int_rate: float64
 loan_percent_income: float64
 cb_person_cred_hist_length: float64
 credit_score: int64 
 previous_loan_defaults_on_file: object 

TARGET_COLUMN:
 loan_status: int64
