artifacts_roots:artifacts 

data_ingestion:
 root_dir:artifacts/data_ingestion
 source_url:https://github.com/mayurkadam9833/Datasets/raw/refs/heads/main/loan_data.zip
 local_data_file:artifacts/data_ingestion/loan_data.zip
 unzip_dir:artifacts/data_ingestion