artifacts_root: artifacts                 # main folder where all outputs/artifacts will be stored

data_ingestion:
 root_dir: artifacts/data_ingestion                                                       # folder for data ingestion step
 source_url: https://github.com/mayurkadam9833/Datasets/raw/refs/heads/main/loan_data.zip # link of dataset
 local_data_file: artifacts/data_ingestion/loan_data.zip                                  # downloaded zip file will be saved here
 unzip_dir: artifacts/data_ingestion                                                      # after unzip the data will be here 

data_validation:
 root_dir: artifacts/data_validation                            # folder for data validation step
 unzip_data: artifacts/data_ingestion/loan_data.csv             # unzip data path for dataset
 STATUS_FILE: artifacts/data_validation/validation_status.txt   # validation file path

data_transformation:
 root_dir: artifacts/data_transformation                # folder for data tarnsformation step
 data_path: artifacts/data_ingestion/loan_data.csv      # extract dataset path

model_trainer:
 root_dir: artifacts/model_trainer                              # folder for model trainer step
 train_data_path: artifacts/data_transformation/train_data.csv  # train data path
 model_name: model.joblib                                       # trained model will be saved with this name

model_evaluation:
 root_dir: artifacts/model_evaluation                                  # folder for model evaluation step
 test_data_path: artifacts/data_transformation/test_data.csv           # test data path
 model_path: artifacts/model_trainer/model.joblib                      # trained model path
 evaluation_file: artifacts/model_evaluation/evaluation_metrics.json   # evalutaion metrics file path
 